### PR TITLE
Improve useragent

### PR DESCRIPTION
**Pull request by LeMyst**
Allow the operator to specify a string that will be prepend to the User-Agent.
Improve #181

### CODE REVIEW

**Comment by dpriskorn** [comment]
Nice idea, but this does not solve the statistics issue does it?

**Comment by LeMyst** [comment]
I made important changes to the PR.
Now the operator can define the USER_AGENT variable and this will be prepend to the User-Agent set by Wikibase Integrator.
It's now impossible to remove "WikibaseIntegrator" from the User-Agent.

**Review by dpriskorn — APPROVED** [review]

**Review by dpriskorn — APPROVED** [review]

**Comment by dpriskorn** [comment]
I like this way forward. It makes it easy for both the user and the WMF Operations Team to keep track of what is hitting the endpoints.

**Comment by LeMyst** [comment]
> I like these changes 😄
> It's now easy for both the user to set a user agent and for the WMF Operations Team to keep track of what is hitting the endpoints.
> I still think we should warn the user if no custom user-agent is set. WDYT?

I added a warning message when WMF instances are used and add some unit tests

**Review by dpriskorn — APPROVED** [review]
Very nice!

**Pull request merged**
