### PR TITLE
Change and remove FunctionsEngine functions

### PR DESCRIPTION
**Pull request by LeMyst**
* Add Exception if format is set to something else than json when using `FunctionsEngine.mediawiki_api_call()`.
* Add Python 3.10 CI workflow.
* Remove `pandas` as a dependency.

### BREAKING CHANGES
* Replace `wbi_core.FunctionsEngine` by `wbi_functions`.
* Remove `FunctionsEngine.get_linked_by()` and `FunctionsEngine.delete_item()`. WikibaseIntegrator will only support wikibase-oriented functions. Directly use `wbi_functions.mediawiki_api_call_helper` instead.
* Rename `FunctionsEngine.delete_statement()` to `wbi_functions.remove_claims()`.
  * `revision` parameter in now optional.
  * Add `summary` parameter.
  * Change parameter order.
* Rename `FunctionsEngine.get_search_results()` to `wbi_functions.search_entities()`.
* Remove dataframe support in `wbi_functions.execute_sparql_query`, use [sparqldataframe](https://pypi.org/project/sparqldataframe/) package instead.
* Move format force to json to `wbi_functions.mediawiki_api_call()`.

### CODE REVIEW

**Comment by LeMyst** [comment]
@dpriskorn What do you think about these changes? I remove some API calls who are not wikibase related.

**Comment by dpriskorn** [comment]
> @dpriskorn What do you think about these changes? I remove some API calls who are not wikibase related.

I never used any of them. For the sparql->dataframe I see it as something not belonging in WBI. I recently started using https://github.com/njanakiev/sparqldataframe which works perfect.

**Comment by LeMyst** [comment]
> > @dpriskorn What do you think about these changes? I remove some API calls who are not wikibase related.
> 
> I never used any of them. For the sparql->dataframe I see it as something not belonging in WBI. I recently started using https://github.com/njanakiev/sparqldataframe which works perfect.

sparqldataframe seems to do the same as `execute_sparql_query(query, as_dataframe=True)`

**Comment by LeMyst** [comment]
I removed dataframe support in WikibaseIntegrator.
It was only used in one function and like you said, sparqldataframe do the job.

**Comment by LeMyst** [comment]
Issue with pytest for Python 3.10 check :
https://bugs.python.org/issue43798
Fixed in
https://github.com/pytest-dev/pytest/pull/8540

**Comment by dpriskorn** [comment]
Very nice 😃 Congratulations!

**Pull request merged**
