### PR TITLE
Add missing __init__ method to ModificationFailed

### PR DESCRIPTION
**Pull request by dpriskorn**
Add missing __init__ method to ModificationFailed.

### CODE REVIEW

**Comment by LeMyst** [comment]
Hello @dpriskorn ,
I don't think it's necessary to add the __init__ into the child class. The "pass" keyword already pass everything to the parent class, so the same as you did.
Can you elaborate why you think it's needed ?

**Comment by dpriskorn** [comment]
I get a weird error and my pull request seems to fix that. 🤷‍♂️
I'll report the error.

**Comment by dpriskorn** [comment]
fixes #389

**Comment by LeMyst** [comment]
Hello @dpriskorn ,
I'm a little reluctant to accept this merge.
For me it's more likely a special case with pydantic, that I can't reproduce, even with over complicated case like this:
```python
from pydantic import BaseModel, validate_arguments


class SomeFirst():
    flag: bool = False

    @property
    def test(self):
        return True


class SomeSecond(SomeFirst):
    pass


class SomeThird(BaseModel):
    @validate_arguments(config=dict(arbitrary_types_allowed=True))
    def main(self):
        second = SomeSecond()
        print(second.flag)  # output: False
        print(second.test)


third = SomeThird()
third.main()
```

The `pass` correctly works in this case.

or with this test:
```python
import logging

from pydantic import BaseModel, validate_arguments

from wikibaseintegrator.wbi_exceptions import ModificationFailed
logger = logging.getLogger(__name__)

class SomeThird(BaseModel):
    @validate_arguments(config=dict(arbitrary_types_allowed=True))
    def main(self):
        error_dict = {'error': {'*': 'See https://test.wikidata.org/w/api.php for API usage. '
                                     'Subscribe to the mediawiki-api-announce mailing list at '
                                     '&lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; '
                                     'for notice of API deprecations and breaking changes.',
                                'code': 'failed-save',
                                'info': 'The save has failed.',
                                'messages': [{'html': {'*': 'The save has failed.'},
                                              'name': 'wikibase-api-failed-save',
                                              'parameters': []},
                                             {'html': {'*': 'Property <a href="/wiki/Property:P50" '
                                                            'title="Property:P50">P50</a> already '
                                                            'has label "Depiction" associated with '
                                                            'language code en.'},
                                              'name': 'wikibase-validator-label-conflict',
                                              'parameters': ['Depiction',
                                                             'en',
                                                             '[[Item:Q50|Item:Q50]]']},
                                             {'html': {'*': 'Property <a href="/wiki/Property:P50" '
                                                            'title="Property:P50">P50</a> already '
                                                            'has label "representación" associated '
                                                            'with language code es.'},
                                              'name': 'wikibase-validator-label-conflict',
                                              'parameters': ['representación',
                                                             'es',
                                                             '[[Item:Q50|Item:Q50]]']}]},
                      'servedby': 'mw1425'}
        second = ModificationFailed(error_dict=error_dict['error'])
        print(second.get_conflicting_entity_ids[0].replace("Item:", ""))


third = SomeThird()
third.main()
```

Do you think you can write a code who reproduce your issue?

**Comment by LeMyst** [comment]
> Interesting. I not certain it is related to pydantic. What makes you think that?

With the error message in #389

**Pull request closed without merging**
