### PR TITLE
Fix logging and unclear logic in the _ write method

### PR DESCRIPTION
**Pull request by dpriskorn**
This change makes it possible to hide the log message in TUI applications to avoid this:
bild
and get this:
bild

### CODE REVIEW

**Comment by LeMyst** [comment]
I rewrited this part to remove the useless code, but can you explain why you replace exception() by error() ?

**Comment by dpriskorn** [comment]
Yes. It's only an error if you expected the write to be successful. 
It's not an exception if the behavior is foreseeable. 
So I suggest you change all the error/exception logging to a lower level like error or warning. 
Then as a user I can set my log level to CRITICAL and log spam 😀

**Comment by LeMyst** [comment]
After some tests, `logging.exception` should not appear when the log level is set as `logging.CRITICAL` because `exception()` return logs at ERROR level.

```
import logging
logging.basicConfig(level=logging.CRITICAL)
logging.debug('debug')
logging.info('info')
logging.warning('warning')
logging.error('error')
logging.exception('exception')
logging.critical('critical')
```
return only
```
CRITICAL:root:critical
```

**Comment by dpriskorn** [comment]
Okay keep the exception the. I just wanted a way to turn it off and that's impossible if you use the logging module in the code and not an instance of it. 😉

**Comment by dpriskorn** [comment]
Ie never write to logging. 
Do
log = logging.getLogger(__name__) in the top of all files and write to that instead like this
log.debug()

**Comment by LeMyst** [comment]
> Okay keep the exception then. I just wanted a way to turn it off and that's seemingly impossible if you use the logging module in the code and not an instance of it. 😉

> Ie never write to logging. Do log = logging.getLogger(**name**) in the top of all files and write to that instead like this log.debug()

The recent commit 1989590fff66471c122ead66bf867e4fae426479 / #411 replace logging.exception by log.exception, it's better ?

**Comment by LeMyst** [comment]
Invalid because of #410

**Pull request closed without merging**
