### PR TITLE
Support NonUniqueLabelDescriptionPairError in mediawiki_api_call()

### PR DESCRIPTION
**Pull request by dpriskorn**
Raise NonUniqueLabelDescriptionPairError also when the code in ['modification-failed', 'wikibase-validator-label-with-description-conflict']

### CODE REVIEW

**Comment by LeMyst** [comment]
@dpriskorn 
I've updated your code to be more specific and to use the error message name.

**Comment by dpriskorn** [comment]
I'm trying to parse and extract the QID from the response.json() to use it in my code. I see now you already implemented the parsing here https://github.com/LeMyst/WikibaseIntegrator/blob/549008eebdb5e7bfd4d4d07a3704c86870902eef/wikibaseintegrator/wbi_exceptions.py#L27 🤩😅
Perfect!

**Comment by LeMyst** [comment]
I've made a proposition of an alternate PR for this changes there #357 
It's something much more general, to avoid ending up with an infinity of different exceptions.

**Comment by dpriskorn** [comment]
I like your solution, closing

**Pull request closed without merging**
